Repository openshift-assisted/jira-unfurl-bot, pull requests merged in 2024-09, with the labels that each got.

#32 NO-ISSUE: Add renovate config to limit number of PR
  renovate.json
Labels: lgtm, jira/valid-reference, size/S

#40 NO-ISSUE: Fix konflux pipeline
  .tekton/jira-unfurl-bot-saas-main-pull-request.yaml
  .tekton/jira-unfurl-bot-saas-main-push.yaml
Labels: size/XS, jira/valid-reference

#38 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/jira-unfurl-bot-saas-main-pull-request.yaml
  .tekton/jira-unfurl-bot-saas-main-push.yaml
Labels: size/M, lgtm, ok-to-test

#39 MGMT-18431: Upgrade setuptools to mitigate CVE-2024-6345
  requirements.txt
Labels: size/XS, lgtm, jira/valid-reference
